#=====================================
#
# NKD - A simple Jekyll boilerplate
#
# More on Jekyll: http://jekyllrb.com/
#
#=====================================

# This will be the first part of the title tag for your site
# <title> {{site.name}} </title>
# ============================================================
name: "Alexander Russell"
title: "Alexander Russell"

# Populates the meta description for the site. Should be under 150 characters for best SEO results.
# ============================================================
description: "Alexander Russell is a desginer who wants to work with you. Alex partners with startups, small organizations, and non-profits to re-think design strategies or invent new ones. Product Design, Graphic Design, UI UX, Web Design."

# Owner (organization or individual) of site content - You'll want to change this from mrmrs :)
# ============================================================
author: "alexanderussell"

# Change this to your production URL
# ============================================================
url: "http://alexanderussell.org"

# Publish future posts or not option.
# ============================================================
future: true

mailchimp:
  user-id: REPLACEME
  list-id: 0b7dc58633

# "A list of directories (including trailing slash) and files to exclude from the conversion"
# I normally exclude _sass, README*, and .gitignore
# Directories that start with an underscore _ are not copied over by default. Still like to include _sass anyways.
# ============================================================
exclude: [README.md, Rakefile, node_modules]

# Pagination variable for how many posts to show in a list
# ============================================================
#paginate: 5

# Style of permalinks
# ============================================================
permalink: none

markdown: kramdown
highlighter: rouge

# Variable format options for URL styles below
# ============================================================
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-:day-:year/:title.html/                 => 04-29-2009/slap-chop.html
# /blog/:year/:month/:day/:title                  => /blog/2009/04/29/slap-chop/index.html


